### ISSUE TITLE
New release delete master

### ISSUE THREAD

**Issue by davetcoleman** [PickNikRobotics/graph_msgs#1]
And switch to *-devel convention

**Comment by progtologist** [comment]
Shouldn't this issue be closed (resolved)?

**Comment by davetcoleman** [comment]
I can't remember if this is fixed, but next time I release this package into bloom i was trying to remind myself to check that the right branch is used because previously it was "master"

**Comment by VictorLamoine** [comment]
@davetcoleman Can you release this package to melodic?
It would simplify the installation of `rviz_visual_tools` on ROS Melodic!

Cheers

**Comment by davetcoleman** [comment]
Done https://github.com/ros/rosdistro/pull/18058
